#!/usr/bin/env node
// PreToolUse hook for Edit|Write: blocks hand edits to files that
// `npm run regen` derives, before the edit lands rather than when
// validate:regen fails in CI. Exit 2 blocks the tool call and feeds the
// stderr message back to Claude; anything else lets the call through.
//
// Only files scripts/lib/derive.mjs writes WHOLLY are guarded. README.md,
// CATALOG.md and the tree READMEs are not: derive.mjs preserves their
// hand-written prose and replaces only the derived regions, so editing that
// prose is legitimate.

import path from 'node:path';
import { pathToFileURL } from 'node:url';

/** Repo-relative paths written wholly by scripts/lib/derive.mjs. */
export const DERIVED_FILES = new Set(['PATHS.md', 'READINESS.md', 'ASSUMPTIONS.md']);

/**
 * The reason a path must not be hand-edited, or null when it may be.
 * `file` may be absolute; `root` is the repository root.
 */
export function derivedReason(file, root) {
  const rel = path.relative(root, path.resolve(root, file)).split(path.sep).join('/');
  if (rel.startsWith('..')) return null;
  if (DERIVED_FILES.has(rel)) {
    return `${rel} is generated by \`npm run regen\` from data/catalog.json (and the leaves); edit the source and regenerate instead.`;
  }
  // Branch READMEs (docs/<tree>/<branch>/README.md) are rendered whole from
  // the catalog. Tree READMEs (one level up) and fixture READMEs (deeper)
  // are hand-written and stay editable.
  if (/^docs\/[^/]+\/[^/]+\/README\.md$/.test(rel)) {
    return `${rel} is a generated branch README; change data/catalog.json and run \`npm run regen\`.`;
  }
  return null;
}

async function main() {
  let raw = '';
  for await (const chunk of process.stdin) raw += chunk;
  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    return 0; // Not a hook payload; never block on our own parse failure.
  }
  const file = input?.tool_input?.file_path;
  if (typeof file !== 'string') return 0;
  const root = process.env.CLAUDE_PROJECT_DIR || input.cwd || process.cwd();
  const reason = derivedReason(file, root);
  if (!reason) return 0;
  process.stderr.write(`Blocked: ${reason}\n`);
  return 2;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exit(await main());
}
